language: java
sudo: false

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10
  - oraclejdk11
  - openjdk11

matrix:
  fast_finish: true
  allow_failures:
  - jdk: oraclejdk11
  - jdk: openjdk11

cache:
    directories:
    - $HOME/.m2

before_script:
  - export MAVEN_SKIP_RC=true

script: mvn clean verify

after_script:
  - cat target/it/tests/IT-*/build.log

after_success:
  - bash <(curl -s https://codecov.io/bash)
