language: java
sudo: false

jdk:
  - oraclejdk8

cache:
    directories:
    - $HOME/.m2

before_script:
  - export MAVEN_SKIP_RC=true

script: mvn clean verify

after_script:
  - cat target/it/tests/IT-*/build.log

after_success:
  - bash <(curl -s https://codecov.io/bash)
