language: java
sudo: false

jdk:
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

matrix:
  fast_finish: true

cache:
    directories:
    - $HOME/.m2

before_script:
  - export MAVEN_SKIP_RC=true

script: mvn clean verify

after_script:
  - cat target/it/tests/IT-*/build.log

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  irc:
    channels:
    - "chat.freenode.net#nicoulaj"
    on_success: never
    on_failure: change
    on_start: never
    use_notice: true
    template:
    - "%{repository}/%{branch}#%{build_number}: %{message} | changes : %{compare_url} | build : %{build_url}"
