name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
        java: [ '8', '9', '10', '11', '12', '13', '14' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} / Java ${{ matrix.java }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}

    - name: Build
      run: mvn --batch-mode verify --file pom.xml

    - name: Archive integration test logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: integration test logs
        path: target/it/tests/**/build.log

    - name: Upload unit test coverage reports
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ matrix.os }}
        JAVA_VERSION: ${{ matrix.java }}
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unit
        env_vars: OS,JAVA_VERSION
        fail_ci_if_error: true

    - name: Upload integration test coverage reports
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ matrix.os }}
        JAVA_VERSION: ${{ matrix.java }}
      with:
        file: ./target/site/jacoco-it/jacoco.xml
        flags: integration
        env_vars: OS,JAVA_VERSION
        fail_ci_if_error: true
