name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        java: [ '8', '9', '10', '11', '12', '13', '14' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} / java ${{ matrix.java }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}

    - name: Build
      run: mvn --batch-mode verify --file pom.xml

    - name: Archive integration test logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: failed integration test logs on ${{ matrix.os }} / java ${{ matrix.java }}
        path: ./target/it/tests/*/build.log

    - name: Upload unit test coverage reports
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ matrix.os }}
        JAVA_VERSION: ${{ matrix.java }}
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unit
        env_vars: OS,JAVA_VERSION

    - name: Upload integration test coverage reports
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ matrix.os }}
        JAVA_VERSION: ${{ matrix.java }}
      with:
        file: ./target/site/jacoco-it/jacoco.xml
        flags: integration
        env_vars: OS,JAVA_VERSION

    - name: Publish snapshot to Github Packages repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/master' && matrix.os == 'ubuntu-latest' && matrix.java == '8'
      run: mvn --batch-mode deploy -Dregistry=https://maven.pkg.github.com/nicoulaj -Dtoken=${{secrets.DEPLOY_GITHUB_PACKAGES_TOKEN}}
