name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '9', '10', '11', '12', '13', '14' ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup JDK
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}

    - name: Build
      run: mvn -B package --file pom.xml

    - uses: codecov/codecov-action@v1
      env:
        JAVA_VERSION: ${{ matrix.java }}
      with:
        env_vars: OS,JAVA_VERSION

    - name: Archive integration test logs
      uses: actions/upload-artifact@v1
      with:
        name: integration test logs
        path: target/it/tests/IT-*/build.log
